version: "3.9"

services:
  express-app:
    image: zamshed/assignment-3-express-app:latest
    container_name: express-app
    networks:
      - app-network
    ports:
      - "3000:3000"  # expose port 3000 for direct access (optional)

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - express-app
    ports:
      - "8080:80"  # access nginx on localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
